version: "3.9"

services:
  # ======================
  # 🧑 USER SERVICE
  # ======================
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8081:8080"
    depends_on:
      - user-db
    env_file:
      - ./user-service/.env
    networks:
      - restaurant-net

  user-db:
    image: postgres:16
    container_name: user-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: restro_user_dev
    ports:
      - "5433:5432"
    volumes:
      - user-data:/var/lib/postgresql/data
    networks:
      - restaurant-net

  # ======================
  # 🍔 MENU SERVICE
  # ======================
  menu-service:
    build: ./menu-service
    container_name: menu-service
    ports:
      - "8082:8080"
    depends_on:
      - menu-db
    env_file:
      - ./menu-service/.env
    networks:
      - restaurant-net

  menu-db:
    image: postgres:16
    container_name: menu-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: restro_menu_dev
    ports:
      - "5434:5432"
    volumes:
      - menu-data:/var/lib/postgresql/data
    networks:
      - restaurant-net

  # ======================
  # 🧾 ORDER SERVICE
  # ======================
  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8083:8080"
    depends_on:
      - order-db
    env_file:
      - ./order-service/.env
    networks:
      - restaurant-net

  order-db:
    image: postgres:16
    container_name: order-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: restro_order_dev
    ports:
      - "5435:5432"
    volumes:
      - order-data:/var/lib/postgresql/data
    networks:
      - restaurant-net

  # ======================
  # 💳 PAYMENT SERVICE
  # ======================
  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "8084:8080"
    depends_on:
      - payment-db
    env_file:
      - ./payment-service/.env
    networks:
      - restaurant-net

  payment-db:
    image: postgres:16
    container_name: payment-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: restro_payment_dev
    ports:
      - "5436:5432"
    volumes:
      - payment-data:/var/lib/postgresql/data
    networks:
      - restaurant-net

# ======================
# SHARED NETWORK & VOLUMES
# ======================
networks:
  restaurant-net:
    driver: bridge

volumes:
  user-data:
  menu-data:
  order-data:
  payment-data:
